<a href="https://colab.research.google.com/github/SDlel/ml-assignments/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SDlel/ml-assignments/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*
One row represents the daily performance of a single content page for one client on one reporting date. For this project, I will build and test features using a mid-panel month such as March 2026. Using a middle month helps avoid using future information when developing the model and leaves later data available for evaluation.

In [1]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
from datasets import load_dataset

ds = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    split="train",
    streaming=True,
)

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [2]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
first_row = next(iter(ds))

print(first_row.keys())

dict_keys(['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'])


## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

The queries confirm that my unit of analysis is correct. Each row represents a content page for a client on a single reporting date. The March 2026 partition contains 9,841,378 rows covering 2026-03-01 through 2026-03-31. After filtering for rows where both gsc_data_available and ga4_data_available are TRUE, 364,347 rows remain for feature development.

In [10]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd

df = pd.read_parquet(path)

print(df.shape)
df.head()

print("Query 1: Grain")
print(df[["client_hash_id", "content_hash_id", "report_date"]].head())

print("\nQuery 2: Row count and date window")
print("Rows:", len(df))
print("Date range:", df["report_date"].min(), "to", df["report_date"].max())

print("\nQuery 3: Availability")
available = df[
    df["gsc_data_available"].eq(True) &
    df["ga4_data_available"].eq(True)
]

print("Rows with both sources available:", len(available))

(9841378, 30)
Query 1: Grain
            client_hash_id           content_hash_id report_date
0  client_73cda7b4e4f265ea  content_b7e512995f79d5a6  2026-03-01
1  client_73cda7b4e4f265ea  content_05597932fe4da067  2026-03-01
2  client_73cda7b4e4f265ea  content_7a105f548d9c6916  2026-03-01
3  client_73cda7b4e4f265ea  content_905aa32a0230694e  2026-03-01
4  client_73cda7b4e4f265ea  content_a3ea9792f793ec72  2026-03-01

Query 2: Row count and date window
Rows: 9841378
Date range: 2026-03-01 to 2026-03-31

Query 3: Availability
Rows with both sources available: 364347


## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

This dataset contains observed search and analytics measurements, but it cannot explain why a page gained or lost traffic. In the March 2026 data, only 364,347 of the 9,841,378 rows have both GSC and GA4 data available, so many rows cannot be used for feature development without additional filtering. The data should be used for decision support rather than causal conclusions.

In [11]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
print("Total rows:", len(df))
print("Rows with both GSC and GA4 available:", len(available))
print("Rows excluded:", len(df) - len(available))


Total rows: 9841378
Rows with both GSC and GA4 available: 364347
Rows excluded: 9477031


## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.